using MiniErp.Domain.Enums;

namespace MiniErp.Application.Features.ProfitabilityReports;

public sealed record ProfitabilityReportLineResponse(
    int InvoiceLineId,
    int InvoiceId,
    string InvoiceNumber,
    DateOnly InvoiceDate,
    InvoiceType InvoiceType,
    int BusinessPartnerId,
    string BusinessPartnerName,
    int StoreId,
    string StoreName,
    int ItemId,
    string ItemCode,
    string ItemName,
    string ItemUnitName,
    decimal Quantity,
    decimal BaseUnitPrice,
    decimal GrossRevenue,
    decimal DiscountAmount,
    decimal NetRevenue,
    InventoryCostStatus CostStatus,
    decimal PendingCostQuantity,
    decimal? UnitCost,
    decimal RecognizedCost,
    decimal? GrossProfit,
    decimal? GrossMarginPercentage);

public sealed record InvoiceProfitabilityResponse(
    int InvoiceId,
    string InvoiceNumber,
    DateOnly InvoiceDate,
    InvoiceType InvoiceType,
    int BusinessPartnerId,
    string BusinessPartnerName,
    int StoreId,
    string StoreName,
    decimal GrossRevenue,
    decimal DiscountAmount,
    decimal NetRevenue,
    decimal RecognizedCost,
    decimal? GrossProfit,
    decimal? GrossMarginPercentage,
    InventoryCostStatus CostStatus,
    decimal PendingCostQuantity,
    int LineCount,
    IReadOnlyList<ProfitabilityReportLineResponse> Lines);

public sealed record InvoiceProfitabilityListItemResponse(
    int InvoiceId,
    string InvoiceNumber,
    DateOnly InvoiceDate,
    InvoiceType InvoiceType,
    int BusinessPartnerId,
    string BusinessPartnerName,
    int StoreId,
    string StoreName,
    decimal GrossRevenue,
    decimal DiscountAmount,
    decimal NetRevenue,
    decimal RecognizedCost,
    decimal? GrossProfit,
    decimal? GrossMarginPercentage,
    InventoryCostStatus CostStatus,
    decimal PendingCostQuantity,
    int LineCount);

public sealed record ProfitabilityReportSummaryResponse(
    decimal SalesRevenue,
    decimal SalesCost,
    decimal ReturnRevenue,
    decimal ReturnCost,
    decimal NetRevenue,
    decimal RecognizedCost,
    decimal? GrossProfit,
    decimal? GrossMarginPercentage,
    decimal FinalizedNetRevenue,
    decimal FinalizedCost,
    decimal FinalizedGrossProfit,
    decimal? FinalizedGrossMarginPercentage,
    decimal PendingRevenue,
    decimal PendingCostQuantity,
    int InvoiceCount,
    int ItemCount,
    int LineCount,
    int PendingInvoiceCount,
    int PendingLineCount);

public sealed record InvoiceProfitabilityListResponse(
    bool IncludeReturns,
    CurrencyCode BaseCurrency,
    DateOnly? FromDate,
    DateOnly? ToDate,
    IReadOnlyList<InvoiceProfitabilityListItemResponse> Invoices,
    int PageNumber,
    int PageSize,
    int TotalCount,
    int TotalPages,
    ProfitabilityReportSummaryResponse Summary);

public sealed record ItemProfitabilityResponse(
    int ItemId,
    string ItemCode,
    string ItemName,
    string ItemUnitName,
    decimal SalesQuantity,
    decimal ReturnQuantity,
    decimal NetQuantity,
    decimal SalesRevenue,
    decimal SalesCost,
    decimal ReturnRevenue,
    decimal ReturnCost,
    decimal NetRevenue,
    decimal RecognizedCost,
    decimal? GrossProfit,
    decimal? GrossMarginPercentage,
    InventoryCostStatus CostStatus,
    decimal PendingCostQuantity,
    int InvoiceCount,
    int LineCount,
    int PendingLineCount);

public sealed record ItemProfitabilityListResponse(
    bool IncludeReturns,
    CurrencyCode BaseCurrency,
    DateOnly? FromDate,
    DateOnly? ToDate,
    IReadOnlyList<ItemProfitabilityResponse> Items,
    int PageNumber,
    int PageSize,
    int TotalCount,
    int TotalPages,
    ProfitabilityReportSummaryResponse Summary);
