using Microsoft.EntityFrameworkCore;
using MiniErp.Application.Common.Models;
using MiniErp.Application.Features.EmployeeOpeningBalances;
using MiniErp.Domain.Enums;
using MiniErp.Tests.PayrollEntries;
using System;
using System.Threading.Tasks;
using Xunit;

namespace MiniErp.Tests.EmployeeFinancials;

public sealed class EmployeeOpeningBalanceServiceTests
{
    [Fact]
    public async Task AddAsync_ShouldCreateOpeningBalance_WithAutoGeneratedDocumentNumber()
    {
        // Arrange
        await using var database = await PayrollEntryTestDatabase.CreateAsync(companyId: 1);
        var service = database.CreateOpeningBalanceService();

        var request = new EmployeeOpeningBalanceRequest(
            EmployeeId: 1,
            DocumentDate: new DateOnly(2026, 8, 1),
            Currency: CurrencyCode.EGP,
            BalanceType: EmployeeBalanceType.Credit,
            Amount: 5000m,
            Notes: "Initial credit opening balance");

        // Act
        var result = await service.AddAsync(request);

        // Assert
        Assert.True(result.IsSuccess);
        Assert.Equal(1, result.Value.EmployeeId);
        Assert.Equal("Monthly Employee", result.Value.EmployeeName);
        Assert.Equal("Emp-001", result.Value.EmployeeCode);
        Assert.Equal(5000m, result.Value.Amount);
        Assert.Equal(EmployeeBalanceType.Credit, result.Value.BalanceType);
        Assert.StartsWith("EOB-", result.Value.DocumentNumber);
        Assert.Null(result.Value.PayrollEntryId);
    }

    [Fact]
    public async Task UpdateAsync_And_DeleteAsync_ShouldFail_WhenBalanceGeneratedByPayroll()
    {
        // Arrange
        await using var database = await PayrollEntryTestDatabase.CreateAsync(companyId: 1);
        var payrollService = database.CreatePayrollService();
        var balanceService = database.CreateOpeningBalanceService();

        for (var day = 1; day <= 5; day++)
        {
            database.Context.EmployeeAttendances.Add(
                new MiniErp.Domain.Entities.Employees.EmployeeAttendance
                {
                    CompanyId = 1,
                    EmployeeId = 1,
                    WorkDate = new DateOnly(2026, 8, day),
                    Status = EmployeeAttendanceStatus.Present,
                    WorkDayRatio = WorkDayRatio.FullDay
                });
        }
        await database.Context.SaveChangesAsync();

        // Create payroll entry and move salary
        var addResult = await payrollService.AddAsync(new Application.Features.PayrollEntries.PayrollEntryCreateRequest(
            EmployeeId: 1,
            EndDate: new DateOnly(2026, 8, 5)));
        Assert.True(addResult.IsSuccess);

        var moveResult = await payrollService.MoveSalaryForEmployeeAccountAsync(
            addResult.Value.Id,
            new Application.Features.PayrollEntries.PayrollEntrySalaryPaymentRequest(
                PostingDate: new DateOnly(2026, 8, 6)));
        Assert.True(moveResult.IsSuccess);

        var openingBalance = await database.Context.EmployeeOpeningBalances
            .FirstAsync(b => b.PayrollEntryId == addResult.Value.Id);

        // Act - Try updating payroll-generated balance directly
        var updateResult = await balanceService.UpdateAsync(
            openingBalance.Id,
            new EmployeeOpeningBalanceUpdateRequest(
                EmployeeId: 1,
                DocumentDate: new DateOnly(2026, 8, 6),
                Currency: CurrencyCode.EGP,
                BalanceType: EmployeeBalanceType.Credit,
                Amount: 9999m,
                Notes: "Illegal modification",
                RowVersion: openingBalance.RowVersion));

        // Assert - Rejected
        Assert.True(updateResult.IsFailure);
        Assert.Equal("EmployeeOpeningBalances.CannotModifyPayrollGenerated", updateResult.Error.Code);

        // Act - Try deleting payroll-generated balance directly
        var deleteResult = await balanceService.DeleteAsync(openingBalance.Id);

        // Assert - Rejected
        Assert.True(deleteResult.IsFailure);
        Assert.Equal("EmployeeOpeningBalances.CannotDeletePayrollGenerated", deleteResult.Error.Code);
    }

    [Fact]
    public async Task GetAllAsync_ShouldFilterByEmployeeAndDateRange()
    {
        // Arrange
        await using var database = await PayrollEntryTestDatabase.CreateAsync(companyId: 1);
        var service = database.CreateOpeningBalanceService();

        await service.AddAsync(new EmployeeOpeningBalanceRequest(
            EmployeeId: 1,
            DocumentDate: new DateOnly(2026, 7, 1),
            Currency: CurrencyCode.EGP,
            BalanceType: EmployeeBalanceType.Credit,
            Amount: 1000m,
            Notes: "July balance"));

        await service.AddAsync(new EmployeeOpeningBalanceRequest(
            EmployeeId: 1,
            DocumentDate: new DateOnly(2026, 8, 1),
            Currency: CurrencyCode.EGP,
            BalanceType: EmployeeBalanceType.Credit,
            Amount: 2000m,
            Notes: "August balance"));

        await service.AddAsync(new EmployeeOpeningBalanceRequest(
            EmployeeId: 2,
            DocumentDate: new DateOnly(2026, 8, 1),
            Currency: CurrencyCode.EGP,
            BalanceType: EmployeeBalanceType.Debit,
            Amount: 500m,
            Notes: "Emp 2 balance"));

        // Act
        var result = await service.GetAllAsync(
            new PaginationRequest { PageNumber = 1, PageSize = 10 },
            new EmployeeOpeningBalanceFilterRequest
            {
                EmployeeId = 1,
                FromDate = new DateOnly(2026, 7, 15)
            });

        // Assert
        Assert.True(result.IsSuccess);
        Assert.Single(result.Value.Items);
        Assert.Equal(2000m, result.Value.Items[0].Amount);
    }

    [Fact]
    public async Task GetAllAsync_DefaultsToCurrentFiscalYearAndAllowsHistoricalYear()
    {
        await using var database =
            await PayrollEntryTestDatabase.CreateAsync(companyId: 1);
        await database.ConfigureSeparateFiscalYearsAsync();
        var service = database.CreateOpeningBalanceService();

        var currentCreated = await service.AddAsync(
            new EmployeeOpeningBalanceRequest(
                EmployeeId: 1,
                DocumentDate: new DateOnly(2025, 1, 1),
                Currency: CurrencyCode.EGP,
                BalanceType: EmployeeBalanceType.Credit,
                Amount: 1000m,
                Notes: "2025 opening"));
        var nextCreated = await service.AddAsync(
            new EmployeeOpeningBalanceRequest(
                EmployeeId: 1,
                DocumentDate: new DateOnly(2026, 1, 1),
                Currency: CurrencyCode.EGP,
                BalanceType: EmployeeBalanceType.Credit,
                Amount: 2000m,
                Notes: "2026 opening"));

        Assert.True(currentCreated.IsSuccess);
        Assert.True(nextCreated.IsSuccess);

        var currentYear = await service.GetAllAsync(
            new PaginationRequest { PageNumber = 1, PageSize = 20 });
        var nextYear = await service.GetAllAsync(
            new PaginationRequest { PageNumber = 1, PageSize = 20 },
            new EmployeeOpeningBalanceFilterRequest
            {
                FiscalYearId = 100
            });

        Assert.True(currentYear.IsSuccess);
        var currentItem = Assert.Single(currentYear.Value.Items);
        Assert.Equal(currentCreated.Value.Id, currentItem.Id);
        Assert.Equal(1, currentItem.FiscalYearId);
        Assert.Equal("2025", currentItem.FiscalYearName);

        Assert.True(nextYear.IsSuccess);
        var nextItem = Assert.Single(nextYear.Value.Items);
        Assert.Equal(nextCreated.Value.Id, nextItem.Id);
        Assert.Equal(100, nextItem.FiscalYearId);
        Assert.Equal("2026", nextItem.FiscalYearName);

        var hiddenNextYearBalance = await service.GetByIdAsync(nextItem.Id);
        var explicitNextYearBalance = await service.GetByIdAsync(
            nextItem.Id,
            fiscalYearId: 100);
        var invalidCurrentYearRange = await service.GetAllAsync(
            new PaginationRequest { PageNumber = 1, PageSize = 20 },
            new EmployeeOpeningBalanceFilterRequest
            {
                FromDate = new DateOnly(2026, 1, 1)
            });
        var crossYearUpdate = await service.UpdateAsync(
            currentCreated.Value.Id,
            new EmployeeOpeningBalanceUpdateRequest(
                EmployeeId: currentCreated.Value.EmployeeId,
                DocumentDate: new DateOnly(2026, 1, 1),
                Currency: currentCreated.Value.Currency,
                BalanceType: currentCreated.Value.BalanceType,
                Amount: currentCreated.Value.Amount,
                Notes: currentCreated.Value.Notes,
                RowVersion: currentCreated.Value.RowVersion));

        Assert.True(hiddenNextYearBalance.IsFailure);
        Assert.Equal(
            "EmployeeOpeningBalances.NotFound",
            hiddenNextYearBalance.Error.Code);
        Assert.True(explicitNextYearBalance.IsSuccess);
        Assert.Equal(nextItem.Id, explicitNextYearBalance.Value.Id);
        Assert.True(invalidCurrentYearRange.IsFailure);
        Assert.Equal(
            "FiscalYears.QueryDateOutsideRange",
            invalidCurrentYearRange.Error.Code);
        Assert.True(crossYearUpdate.IsFailure);
        Assert.Equal(
            "FiscalYears.QueryDateOutsideRange",
            crossYearUpdate.Error.Code);
    }
}
