using Microsoft.EntityFrameworkCore;
using MiniErp.Application.Common.Models;
using MiniErp.Application.Features.EmployeeOpeningBalances;
using MiniErp.Domain.Enums;
using MiniErp.Tests.PayrollEntries;
using System;
using System.Threading.Tasks;
using Xunit;

namespace MiniErp.Tests.EmployeeFinancials;

public sealed class EmployeeOpeningBalanceServiceTests
{
    [Fact]
    public async Task AddAsync_ShouldCreateOpeningBalance_WithAutoGeneratedDocumentNumber()
    {
        // Arrange
        await using var database = await PayrollEntryTestDatabase.CreateAsync(companyId: 1);
        var service = database.CreateOpeningBalanceService();

        var request = new EmployeeOpeningBalanceRequest(
            EmployeeId: 1,
            DocumentDate: new DateOnly(2026, 8, 1),
            Currency: CurrencyCode.EGP,
            BalanceType: EmployeeBalanceType.Credit,
            Amount: 5000m,
            Notes: "Initial credit opening balance");

        // Act
        var result = await service.AddAsync(request);

        // Assert
        Assert.True(result.IsSuccess);
        Assert.Equal(1, result.Value.EmployeeId);
        Assert.Equal("Monthly Employee", result.Value.EmployeeName);
        Assert.Equal("EMP001", result.Value.EmployeeCode);
        Assert.Equal(5000m, result.Value.Amount);
        Assert.Equal(EmployeeBalanceType.Credit, result.Value.BalanceType);
        Assert.StartsWith("EOB-", result.Value.DocumentNumber);
        Assert.Null(result.Value.PayrollEntryId);
    }

    [Fact]
    public async Task UpdateAsync_And_DeleteAsync_ShouldFail_WhenBalanceGeneratedByPayroll()
    {
        // Arrange
        await using var database = await PayrollEntryTestDatabase.CreateAsync(companyId: 1);
        var payrollService = database.CreatePayrollService();
        var balanceService = database.CreateOpeningBalanceService();

        // Create payroll entry and move salary
        var addResult = await payrollService.AddAsync(new Application.Features.PayrollEntries.PayrollEntryCreateRequest(
            StartDate: new DateOnly(2026, 8, 1),
            EndDate: new DateOnly(2026, 8, 5),
            EmployeeId: 1));
        Assert.True(addResult.IsSuccess);

        var moveResult = await payrollService.MoveSalaryForEmployeeAccountAsync(
            addResult.Value.Id,
            new Application.Features.PayrollEntries.PayrollEntrySalaryPaymentRequest(
                PostingDate: new DateOnly(2026, 8, 6)));
        Assert.True(moveResult.IsSuccess);

        var openingBalance = await database.Context.EmployeeOpeningBalances
            .FirstAsync(b => b.PayrollEntryId == addResult.Value.Id);

        // Act - Try updating payroll-generated balance directly
        var updateResult = await balanceService.UpdateAsync(
            openingBalance.Id,
            new EmployeeOpeningBalanceUpdateRequest(
                EmployeeId: 1,
                DocumentDate: new DateOnly(2026, 8, 6),
                Currency: CurrencyCode.EGP,
                BalanceType: EmployeeBalanceType.Credit,
                Amount: 9999m,
                Notes: "Illegal modification",
                RowVersion: openingBalance.RowVersion));

        // Assert - Rejected
        Assert.True(updateResult.IsFailure);
        Assert.Equal("EmployeeOpeningBalances.CannotModifyPayrollGenerated", updateResult.Error.Code);

        // Act - Try deleting payroll-generated balance directly
        var deleteResult = await balanceService.DeleteAsync(openingBalance.Id);

        // Assert - Rejected
        Assert.True(deleteResult.IsFailure);
        Assert.Equal("EmployeeOpeningBalances.CannotDeletePayrollGenerated", deleteResult.Error.Code);
    }

    [Fact]
    public async Task GetAllAsync_ShouldFilterByEmployeeAndDateRange()
    {
        // Arrange
        await using var database = await PayrollEntryTestDatabase.CreateAsync(companyId: 1);
        var service = database.CreateOpeningBalanceService();

        await service.AddAsync(new EmployeeOpeningBalanceRequest(
            EmployeeId: 1,
            DocumentDate: new DateOnly(2026, 7, 1),
            Currency: CurrencyCode.EGP,
            BalanceType: EmployeeBalanceType.Credit,
            Amount: 1000m,
            Notes: "July balance"));

        await service.AddAsync(new EmployeeOpeningBalanceRequest(
            EmployeeId: 1,
            DocumentDate: new DateOnly(2026, 8, 1),
            Currency: CurrencyCode.EGP,
            BalanceType: EmployeeBalanceType.Credit,
            Amount: 2000m,
            Notes: "August balance"));

        await service.AddAsync(new EmployeeOpeningBalanceRequest(
            EmployeeId: 2,
            DocumentDate: new DateOnly(2026, 8, 1),
            Currency: CurrencyCode.EGP,
            BalanceType: EmployeeBalanceType.Debit,
            Amount: 500m,
            Notes: "Emp 2 balance"));

        // Act
        var result = await service.GetAllAsync(
            new PaginationRequest { PageNumber = 1, PageSize = 10 },
            new EmployeeOpeningBalanceFilterRequest
            {
                EmployeeId = 1,
                FromDate = new DateOnly(2026, 7, 15)
            });

        // Assert
        Assert.True(result.IsSuccess);
        Assert.Single(result.Value.Items);
        Assert.Equal(2000m, result.Value.Items[0].Amount);
    }
}
