using Microsoft.OpenApi;
using MiniErp.Api.Controllers;
using Swashbuckle.AspNetCore.SwaggerGen;

namespace MiniErp.Api.Swagger;

public sealed class CashVouchersSwaggerDocumentation : IOperationFilter
{
    public void Apply(
        OpenApiOperation operation,
        OperationFilterContext context)
    {
        if (context.MethodInfo.DeclaringType != typeof(CashVouchersController))
        {
            return;
        }

        var documentation = context.MethodInfo.Name switch
        {
            nameof(CashVouchersController.GetAll) => (
                "Get paginated cash vouchers",
                SwaggerOperationDescription.Create(
                    "Returns active manual and invoice-generated Receipt and Payment vouchers for the selected company. InvoiceId and InvoiceNumber identify generated payment vouchers.",
                    "Optional search, voucherNumber, direction, cashboxId, cashMovementTypeId, classification, partyType, businessPartnerId, driverId, driverTripId, employeeId, isDraft, fromDate, toDate, pageNumber, and pageSize filters.",
                    "Search covers voucher, cashbox, movement type, partner, driver, employee, trip invoice, external party, reference, and description display values.",
                    "Deleted and other-company vouchers are excluded.")),
            nameof(CashVouchersController.GetById) => (
                "Get a cash voucher",
                SwaggerOperationDescription.Create(
                    "Returns one voucher with its draft status, optional cashbox, optional movement type, party, optional source invoice, transaction/base amounts, resolved exchange-rate snapshot, and concurrency token.",
                    "A positive route id.",
                    "Currency is the selected cashbox currency. When it matches baseCurrency, exchangeRate is 1 and baseAmount equals amount. Foreign-currency vouchers return the original amount/currency and its converted baseAmount/baseCurrency snapshot.",
                    "Missing or other-company vouchers return 404.")),
            nameof(CashVouchersController.Create) => (
                "Create a cash voucher",
                SwaggerOperationDescription.Create(
                    "Admin only. Creates a cash-voucher draft linked to the selected cashbox without changing its balance.",
                    "Send exactly `voucherDate`, Receipt or Payment `direction`, an active `cashboxId`, a positive `amount`, and optional `description`. Select a cashbox in the required foreign currency to receive or pay in that currency.",
                    "`voucherNumber` is generated by the server and is not accepted in the create or update request. Complete the remaining posting fields later with PUT.",
                    "The draft creates no cashbox or partner movement until it is completed by an update.")),
            nameof(CashVouchersController.Update) => (
                "Update a cash voucher",
                SwaggerOperationDescription.Create(
                    "Admin only. Replaces a manual draft or completed voucher and all derived effects, including its base-currency snapshot, atomically.",
                    "All completion fields plus the original base64 rowVersion. Voucher number is server-generated, immutable, and is not sent. Party type is derived by the server: send at most one of employeeId, businessPartnerId, driverId, or externalPartyName; omitting all of them means no party. driverTripId is allowed only with driverId.",
                    "An active cashbox and matching active movement type are required. For a foreign-currency cashbox, send exchangeRate or omit it to use the registered rate for the voucher date. The old effects are removed and the completed effects are applied exactly once.",
                    "A stale token returns CashVouchers.Concurrency. An invoice-generated voucher returns CashVouchers.InvoiceGeneratedReadOnly and must be changed through its invoice.")),
            nameof(CashVouchersController.Delete) => (
                "Delete a cash voucher",
                SwaggerOperationDescription.Create(
                    "Admin only. Soft-deletes a manual voucher and its partner movement atomically.",
                    "A positive route id.",
                    "Deleting a receipt is rejected when it would leave its cashbox negative.",
                    "Missing records return 404; concurrency and balance conflicts return 409. Invoice-generated vouchers are read-only and return CashVouchers.InvoiceGeneratedReadOnly.")),
            _ => default
        };

        if (documentation == default)
        {
            return;
        }

        operation.Summary = documentation.Item1;
        operation.Description = documentation.Item2;
        operation.OperationId = $"CashVouchers_{context.MethodInfo.Name}";
    }
}
