using Microsoft.OpenApi;
using MiniErp.Api.Controllers;
using Swashbuckle.AspNetCore.SwaggerGen;

namespace MiniErp.Api.Swagger;

public sealed class CashVouchersSwaggerDocumentation : IOperationFilter
{
    public void Apply(
        OpenApiOperation operation,
        OperationFilterContext context)
    {
        if (context.MethodInfo.DeclaringType != typeof(CashVouchersController))
        {
            return;
        }

        var documentation = context.MethodInfo.Name switch
        {
            nameof(CashVouchersController.GetAll) => (
                "Get paginated cash vouchers",
                SwaggerOperationDescription.Create(
                    "Returns active manual and invoice-generated Receipt and Payment vouchers for the selected company. InvoiceId and InvoiceNumber identify generated payment vouchers.",
                    "Optional search, voucherNumber, direction, cashboxId, cashMovementTypeId, classification, partyType, businessPartnerId, driverId, driverTripId, employeeId, isDraft, fromDate, toDate, pageNumber, and pageSize filters.",
                    "Search covers voucher, cashbox, movement type, partner, driver, employee, trip invoice, external party, reference, and description display values. classification is persisted on the voucher; old rows are read with a movement-type/account fallback.",
                    "Deleted and other-company vouchers are excluded.")),
            nameof(CashVouchersController.GetHandoverReport) => (
                "Get cash handover report",
                SwaggerOperationDescription.Create(
                    "Returns manual cash-voucher drafts that are waiting for accounting completion. These drafts are operational custody records only and do not affect cashbox balances, partner statements, or the general ledger.",
                    "Optional cashboxId, fromDate, toDate, direction, search, pageNumber, and pageSize filters.",
                    "Search covers voucher number, cashbox code/name, description, and notes. The response includes a page of draft items and receipt/payment/net summaries grouped by currency.",
                    "Only drafts belonging to the selected company and not generated by an invoice or cashbox transfer are returned.")),
            nameof(CashVouchersController.GetById) => (
                "Get a cash voucher",
                SwaggerOperationDescription.Create(
                    "Returns one voucher with its draft status, optional cashbox, optional movement descriptor, optional expense/revenue account, party, optional source invoice, transaction/base amounts, resolved exchange-rate snapshot, and concurrency token.",
                    "A positive route id.",
                    "Currency is the selected cashbox currency. When it matches baseCurrency, exchangeRate is 1 and baseAmount equals amount. Foreign-currency vouchers return the original amount/currency and its converted baseAmount/baseCurrency snapshot.",
                    "Missing or other-company vouchers return 404.")),
            nameof(CashVouchersController.GetPartySelect) => (
                "Get cash-voucher party selections",
                SwaggerOperationDescription.Create(
                    "Returns the active business partners, drivers, employees, expenses, and revenues available to cash vouchers for the selected company.",
                    "No request parameters.",
                    "Party collections contain id and name. expenses and revenues contain active posting accounts with id, name, classification, code, and accountType. Every collection is ordered by name then id. Active drivers remain available even when their license is expired.",
                    "Expense accounts are used with Payment vouchers and revenue accounts with Receipt vouchers. Movement descriptors are loaded separately from CashMovementTypes/select; inactive records are excluded.")),
            nameof(CashVouchersController.Create) => (
                "Create a cash voucher",
                SwaggerOperationDescription.Create(
                    "Admin only. Creates a manual cash handover draft linked to the selected active cashbox without accounting or cashbox-balance effects.",
                    "Send `voucherDate`, Receipt or Payment `direction`, an active `cashboxId`, a positive `amount`, and optional `description` or `notes`. No party, account, or movement type is required.",
                    "`voucherNumber` is generated by the server. Complete the posting target later with PUT when the movement should enter the ledger.",
                    "The draft creates no journal, partner movement, employee movement, cashbox balance effect, or accounting-readiness source.")),
            nameof(CashVouchersController.Bulk) => (
                "Apply cash-voucher changes in bulk",
                SwaggerOperationDescription.Create(
                    "Admin only. Applies up to 100 ordered Add, Update, and Delete cash-voucher items as one atomic transaction.",
                    "Each item uses action as its discriminator. Add accepts action and voucher; Update accepts action, id, original base64 rowVersion, and voucher; Delete accepts action, id, and original base64 rowVersion only. cashMovementTypeId is optional for Add and Update.",
                    "The server generates voucher numbers and derives partyType from employeeId, businessPartnerId, driverId, or externalPartyName. Send exactly one posting target from those fields or accountId; cashMovementTypeId is an optional descriptor and must match the voucher direction. When employeeId is supplied, employeeMovementType is required and must match the direction (Credit/Bonus for Receipt, Debit/Deduction for Payment); it creates or updates the linked HR employee movement without duplication. An accountId must be an active posting Expense account for Payment or Revenue account for Receipt. An item cannot target an invoice-generated or cashbox-transfer-generated voucher. If any item fails, every item is rolled back.",
                    "Every Add or Update produces a completed, posted voucher. The response preserves request order and returns one result per request item, including the created or updated voucher; deleted items return voucher as null. Runtime failures identify their Items[index] location.")),
            nameof(CashVouchersController.Update) => (
                "Update a cash voucher",
                SwaggerOperationDescription.Create(
                    "Admin only. Replaces a manual draft or completed voucher and all derived effects, including its base-currency snapshot, atomically.",
                    "All voucher fields plus the original base64 rowVersion. Voucher number is server-generated, immutable, and is not sent. Send exactly one posting target: employeeId, businessPartnerId, driverId, externalPartyName, or accountId. cashMovementTypeId is optional and can be sent with the target as an additional descriptor. driverTripId is allowed only with driverId.",
                    "The posting target allows cashMovementTypeId to be null. The server persists classification from the selected movement type, or Expense/Revenue from a direct account target, so expense screens can filter every source consistently. When supplied, the movement type must be active, match the voucher direction, and a partner-only type cannot be used with a non-partner target. For an employee target, employeeMovementType is required and must match the direction (Credit/Bonus for Receipt, Debit/Deduction for Payment); the linked HR movement is upserted by CashVoucherId. Use Receipt with Revenue account and Payment with Expense account. For a foreign-currency cashbox, send exchangeRate or omit it to use the registered rate for the voucher date.",
                    "Saving produces a completed, posted voucher. A stale token returns CashVouchers.Concurrency. An invoice-generated voucher returns CashVouchers.InvoiceGeneratedReadOnly and must be changed through its invoice.")),
            nameof(CashVouchersController.Delete) => (
                "Delete a cash voucher",
                SwaggerOperationDescription.Create(
                    "Admin only. Soft-deletes a manual voucher and its derived partner or employee movement atomically.",
                    "A positive route id.",
                    "Deleting a receipt is rejected when it would leave its cashbox negative.",
                    "Missing records return 404; concurrency and balance conflicts return 409. Invoice-generated vouchers are read-only and return CashVouchers.InvoiceGeneratedReadOnly.")),
            _ => default
        };

        if (documentation == default)
        {
            return;
        }

        operation.Summary = documentation.Item1;
        operation.Description = documentation.Item2;
        operation.OperationId = $"CashVouchers_{context.MethodInfo.Name}";
    }
}
